{
 "title": "Kowabunga - Computing - Virtual Machines",
 "tags": [
  "libvirt",
  "kvm",
  "kowabunga"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Platform", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(kowabunga_project_allocated_vcpus,name)"
    }
   },
   {
    "name": "vm",
    "label": "Virtual Machine",
    "query": {
     "query": "label_values(kowabunga_instance_settings{project=~\"$project\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Machine Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_state_code{domain=~\"$vm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_instance_settings{name=\"$vm\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "Total CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$vm\"}[5m])",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$vm\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$vm\"}[5m])",
     "legendFormat": "Write "
    }
   ]
  },
  {
   "title": "Block Read/Write Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_read_requests_total{domain=~\"$vm\"}[5m])",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_write_requests_total{domain=~\"$vm\"}[5m])",
     "legendFormat": "Write  Requests"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vNIC Stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{source_bridge}} RX"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{ source_bridge }} TX"
    }
   ]
  },
  {
   "title": "vNIC Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{ source_bridge }} RX Packets"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{ source_bridge }} TX Packets"
    }
   ]
  },
  {
   "title": "vNIC Error/Drop",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{ source_bridge }} RX Drop"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$vm\"} [5m])",
     "legendFormat": "{{source_bridge}} TX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_errors_total{instance=~\"$node.*\",domain=~\".*-$env-.*\",domain=~\"$vm.*\"} [5m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_errors_total{instance=~\"$node\",domain=~\".*-$env-.*\",domain=~\"$vm\"} [5m]))",
     "legendFormat": "TX Error"
    }
   ]
  }
 ]
}