{
 "title": "Kowabunga - Core - Engine",
 "tags": [ "kowabunga" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Platform", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(kowabunga_project_instances,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Projects / Tenants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kowabunga_projects)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Computing Hosts Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kowabunga_host_cost)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Storage Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kowabunga_storage_pools_cost)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spare Public IPv4 Addresses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_public_subnets_ips{type=\"free\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per-Host Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
   "targets": [
    { "expr": "kowabunga_host_instances", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "vCPUs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 6 },
   "targets": [
    { "expr": "kowabunga_host_allocated_vcpus", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kowabunga_host_allocated_memory_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Per-Project Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_instances{name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_allocated_vcpus{name=\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_allocated_memory_bytes{name=\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_volumes{name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_allocated_storage_bytes{name=\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_project_estimated_cost{name=\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}