{
 "title": "Kowabunga - Core - Infrastructure",
 "tags": [
  "kowabunga",
  "linux",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Platform", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_load1,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load [5m average]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$host\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemFree_bytes{instance=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemFree_bytes{instance=~\"$host\"} - node_memory_Buffers_bytes{instance=~\"$host\"} - node_memory_Cached_bytes{instance=~\"$host\"}",
     "legendFormat": "Used (no buffers/cache)"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]) + rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$host\",device!~\"docker0|veth.+|br-.+|lo.*\"}[5m])",
     "legendFormat": "{{ device }} in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$host\",device!~\"docker0|veth.+|br-.+|lo.*\"}[5m]) * -1",
     "legendFormat": "{{ device }} out"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$host\",fstype=\"ext4\"} / node_filesystem_size_bytes{instance=~\"$host\",fstype=\"ext4\"} * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}