{
 "title": "Kowabunga - Overview",
 "tags": [
  "kowabunga",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Platform", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Platform", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Kowabunga Multi-Tenants Virtualization Platform Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<table cellspacing=\"0\" cellpadding=\"0\" style=\"border: none;\">\n    <tr style=\"border: none;\">\n        <td style=\"border: none;\"><img src=\"https://raw.githubusercontent.com/kowabunga-cloud/infographics/master/art/kowabunga-square-600x600-2.png\" width=\"200px\"/></td>\n        <td style=\"border: none;\">\n            <ul>\n                <li><a href=\"/d/bdp5guz8tux34d/kowabunga-core-engine?var-DS_PROMETHEUS=${DS_PROMETHEUS}\">API Engine</a></li>\n                <li><a href=\"/d/edp5v7wukyfpcb/kowabunga-core-infrastructure?var-DS_PROMETHEUS=${DS_PROMETHEUS}\">Core Metal Infrastructure</a></li>\n                <li><a href=\"/d/fdp4na4zm7w1sd/kowabunga-storage-ceph?var-DS_PROMETHEUS=${DS_PROMETHEUS}\">Storage - Ceph</a></li>\n                <li><a href=\"/d/cdp54hs74035sc/kowabunga-computing-kvm-virtual-machines?var-DS_PROMETHEUS=${DS_PROMETHEUS}\">Computing - Per-Tenant Virtual Machines</a></li>\n                <li><a href=\"/explore?schemaVersion=1&datasource=${DS_PROMETHEUS}\">Raw Metrics</a></li>\n                <li><a href=\"/explore?schemaVersion=1&datasource=${DS_LOKI}\">Logs</a></li>\n            </ul>\n        </td>\n    </tr>                                       \n</table>"
   }
  },
  {
   "title": "Projects (Tenants)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kowabunga_projects)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instances State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_state_code) / count(libvirt_domain_state_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioned vCPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kowabunga_project_allocated_vcpus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisoned Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kowabunga_project_volumes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spare Public IPv4 Addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kowabunga_public_subnets_ips{type=\"free\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisoned Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kowabunga_project_instances)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisonned Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kowabunga_project_allocated_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisoned Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kowabunga_project_allocated_storage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KVM Hypervisors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "KVM Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_uname_info{instance=~\".*-kvm-.*\"}) / count(node_uname_info{instance=~\".*-kvm-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\".*-kvm-.*\",mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (avg by (instance) ((node_memory_MemTotal_bytes{instance=~\".*-kvm-.*\"} - node_memory_MemFree_bytes{instance=~\".*-kvm-.*\"} - node_memory_Buffers_bytes{instance=~\".*-kvm-.*\"} - node_memory_Cached_bytes{instance=~\".*-kvm-.*\"}) / node_memory_MemTotal_bytes{instance=~\".*-kvm-.*\"}))",
     "legendFormat": "Used (no buffers/cache)"
    }
   ]
  },
  {
   "title": "Average Private VLAN Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (\n    rate(node_network_receive_bytes_total{instance=~\".*-kvm-.*\",device=~\"vlan[0-9]*\"}[5m]) + \n    rate(node_network_transmit_bytes_total{instance=~\".*-kvm-.*\",device=~\"vlan[0-9]*\"}[5m])\n) * 8 / count(node_uname_info{instance=~\".*-kvm-.*\"})",
     "legendFormat": "VLAN"
    }
   ]
  },
  {
   "title": "Average Public WAN Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (\n    rate(node_network_receive_bytes_total{instance=~\".*-kvm-.*\",device=\"bond0\"}[5m]) + \n    rate(node_network_transmit_bytes_total{instance=~\".*-kvm-.*\",device=\"bond0\"}[5m])\n) * 8 / count(node_uname_info{instance=~\".*-kvm-.*\"}) -\nsum (\n    rate(node_network_receive_bytes_total{instance=~\".*-kvm-.*\",device=~\"vlan[0-9]*\"}[5m]) + \n    rate(node_network_transmit_bytes_total{instance=~\".*-kvm-.*\",device=~\"vlan[0-9]*\"}[5m])\n) * 8 / count(node_uname_info{instance=~\".*-kvm-.*\"})",
     "legendFormat": "WAN"
    }
   ]
  },
  { "title": "Ceph Distributed Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  }
 ]
}