{
 "title": "Kowabunga - Storage - Ceph",
 "description": "Ceph Cluster overview\n",
 "tags": [
  "kowabunga",
  "storage",
  "ceph"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Platform", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CLUSTER STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr_bytes[5m]))"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(irate(ceph_pool_wr[5m]))" }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_wr_bytes)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(irate(ceph_pool_rd[5m]))" }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_rd_bytes)" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_mon_quorum_status)" }
   ]
  },
  {
   "title": "OSD STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in)" }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)" }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)"
    }
   ]
  },
  {
   "title": "CLUSTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" },
      {
       "expr": "ceph_cluster_total_bytes-ceph_cluster_total_used_bytes",
       "legendFormat": "Available"
      },
      { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum(irate(ceph_pool_wr[5m]))", "legendFormat": "Write" },
      { "expr": "sum(irate(ceph_pool_rd[5m]))", "legendFormat": "Read" }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_pool_wr_bytes[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(ceph_pool_rd_bytes[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Pool Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_bytes_used) *on (pool_id) group_left(name)(ceph_pool_metadata)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool RAW Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_stored_raw) *on (pool_id) group_left(name)(ceph_pool_metadata)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Objects Per Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ceph_pool_objects) *on (pool_id) group_left(name)(ceph_pool_metadata)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OBJECTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Objects in the Cluster",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "PGs State",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pg_active)", "legendFormat": "Active" },
      { "expr": "sum(ceph_pg_clean)", "legendFormat": "Clean" },
      { "expr": "sum(ceph_pg_peering)", "legendFormat": "Peering" },
      { "expr": "sum(ceph_pg_degraded)", "legendFormat": "Degraded" },
      { "expr": "sum(ceph_pg_stale)", "legendFormat": "Stale" },
      { "expr": "sum(ceph_pg_undersized)", "legendFormat": "Undersized" },
      { "expr": "sum(ceph_pg_incomplete)", "legendFormat": "Incomplete" },
      { "expr": "sum(ceph_pg_forced_backfill)", "legendFormat": "Forced Backfill" },
      { "expr": "sum(ceph_pg_inconsistent)", "legendFormat": "Inconsistent" },
      { "expr": "sum(ceph_pg_forced_recovery)", "legendFormat": "Forced Recovery" },
      { "expr": "sum(ceph_pg_creating)", "legendFormat": "Creating" },
      { "expr": "sum(ceph_pg_backfill_wait)", "legendFormat": "Wait Backfill" },
      { "expr": "sum(ceph_pg_deep)", "legendFormat": "Deep" },
      { "expr": "sum(ceph_pg_scrubbing)", "legendFormat": "Scrubbing" },
      { "expr": "sum(ceph_pg_recovering)", "legendFormat": "Recovering" },
      { "expr": "sum(ceph_pg_repair)", "legendFormat": "Repair" },
      { "expr": "sum(ceph_pg_down)", "legendFormat": "Down" },
      { "expr": "sum(ceph_pg_peered)", "legendFormat": "Peered" },
      { "expr": "sum(ceph_pg_backfilling)", "legendFormat": "Backfill" },
      { "expr": "sum(ceph_pg_remapped)", "legendFormat": "Remapped" },
      { "expr": "sum(ceph_pg_backfill_toofull)", "legendFormat": "Backfill Toofull" }
     ]
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      { "expr": "ceph_osd_apply_latency_ms" }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      { "expr": "ceph_osd_commit_latency_ms" }
     ]
    }
   ]
  }
 ]
}